name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://huggingface.co/spaces/amely188/P8-project-MLOps-Pret-a-Depenser hf-space
          cd hf-space

          rsync -av --exclude='.git' ../ .

          git add .
          git commit -m "auto deploy"
          git push https://amely188:$HF_TOKEN@huggingface.co/spaces/amely188/P8-project-MLOps-Pret-a-Depenser main